{"name": "test_login_passmiss", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1", "trace": "self = <feature_practice.TestLogin object at 0x000001E9F778C1F0>\n\n    @allure.story(\"密码缺失\")\n    def test_login_passmiss(self):\n        #标记每个登陆步骤，用with allure.step()标记，这样可以在测试报告里看到详细的测试情况\n        with allure.step(\"点击用户名\"):\n            print(\"输入用户名\")\n        with allure.step(\"点击密码\"):\n            print(\"输入密码\")\n        print(\"点击登录\")\n        with allure.step(\"点击登陆之后登录失败\"):\n>           assert '1' == 1\nE           AssertionError: assert '1' == 1\n\nfeature_practice.py:33: AssertionError"}, "steps": [{"name": "点击用户名", "status": "passed", "start": 1605615974953, "stop": 1605615974953}, {"name": "点击密码", "status": "passed", "start": 1605615974953, "stop": 1605615974953}, {"name": "点击登陆之后登录失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n", "trace": "  File \"D:\\pychrm\\Pytest_hogwarts\\pytest_record\\feature_practice.py\", line 33, in test_login_passmiss\n    assert '1' == 1\n"}, "start": 1605615974954, "stop": 1605615974954}], "attachments": [{"name": "stdout", "source": "889b65de-dd43-4bca-a07a-57b36f78bf24-attachment.txt", "type": "text/plain"}], "start": 1605615974953, "stop": 1605615974954, "uuid": "98a63d54-6226-4c56-925a-44d3f27283b5", "historyId": "57d6321754fdad0a1b0b0f30f885a37c", "testCaseId": "5b633defc7c3f4870bf19d9eeed16fcd", "fullName": "feature_practice.TestLogin#test_login_passmiss", "labels": [{"name": "story", "value": "密码缺失"}, {"name": "feature", "value": "登录模块"}, {"name": "suite", "value": "feature_practice"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-95H2SUTO"}, {"name": "thread", "value": "14472-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "feature_practice"}]}