{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\nallure_practice.py:10: AssertionError"}, "description": "this test fails", "start": 1605527730649, "stop": 1605527730649, "uuid": "73092a06-2e38-4017-80d9-e83b6e4d898c", "historyId": "4e3c927840ebdbc67c44a6eac784255c", "testCaseId": "17fc9d6bf68b11f3fe997b9a21c520d1", "fullName": "allure_practice#test_failure", "labels": [{"name": "suite", "value": "allure_practice"}, {"name": "host", "value": "LAPTOP-95H2SUTO"}, {"name": "thread", "value": "23628-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "allure_practice"}]}